spring:
  application:
    name: microservice-boot-provider

nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 2c047fc5-bcf4-47eb-a9ce-f8ef353c49e4
    bootstrap:
      enable: true
    type: yaml
    data-id: microservice-boot-provider
    auto-refresh: true
