spring:
  application:
    name: dubbo3-test-consumer
nacos:
  config:
    server-addr: 10.255.20.232:8848
    namespace: 2c047fc5-bcf4-47eb-a9ce-f8ef353c49e4
    bootstrap:
      enable: true
    type: yaml
    data-id: dubbo3-test-consumer
    auto-refresh: true
